---
- name: Add devops group
  hosts: centos
  become: yes
  tasks:
    - name: Ensure devops group exists
      ansible.builtin.group:
        name: devops
        state: present

    - name: Ensure wheel group exists
      ansible.builtin.group:
        name: wheel
        state: present

    - name: Allow wheel group passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Add deployer user to wheel group
      ansible.builtin.user:
        name: deployer
        groups: wheel
        append: true
        state: present
        create_home: true

    - name: Allow devops group sudo access
      ansible.builtin.blockinfile:
        path: /etc/sudoers
        insertafter: "root    ALL=(ALL)       ALL"
        block: |
          # Gives sudo access to the devops group
          %devops        ALL=(ALL)       NOPASSWD: ALL
