---
- name: Update existing dependencies
  hosts: centos_docker
  become: true
  gather_facts: true
  tasks:
    - name: Upgrade all packages
      ansible.builtin.yum:  # noqa package-latest
        name: "*"
        state: latest
- name: Install dependencies
  hosts: centos_docker
  become: true
  gather_facts: false
  tasks:
    - name: Install python3
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum:
        name: python3
        update_cache: true
        state: present
    - name: Install vim
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum:
        name:
          - vim
          - vim-enhanced
        state: present
        update_cache: true
    - name: Install epel-release
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum:
        name:
          - epel-release
        state: present
        update_cache: true
    - name: Install htop
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum:
        name:
          - htop
        state: present
        update_cache: true
    - name: Install utils
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - unzip
        state: present
        update_cache: true
- name: Install docker
  hosts: centos_docker
  become: true
  gather_facts: true
  tasks:
    - name: Create devops group
      ansible.builtin.group:
        name: devops
        state: present
    - name: Configure Docker CE repository
      ansible.builtin.yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        enabled: true
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/centos/gpg
    - name: Install docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum:
        name: docker-ce
        update_cache: true
        state: present
    - name: Starting docker service
      ansible.builtin.service:
        name: "docker"
        state: started
        enabled: true
- name: Install telegraf
  hosts: centos_docker
  become: true
  gather_facts: true
  tasks:
    - name: Add InfluxDB repository
      ansible.builtin.yum_repository:
        name: influxdb
        description: InfluxDB Repository - RHEL $releasever
        baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
        enabled: true
        gpgcheck: true
        gpgkey: https://repos.influxdata.com/influxdata-archive_compat.key
    - name: Install influxdb
      ansible.builtin.yum:
        name: influxdb
        update_cache: true
        state: present
    - name: Starting docker service
      ansible.builtin.service:
        name: "influxdb"
        state: started
        enabled: true
- name: Install Digital Ocean metrics
  hosts: centos_docker
  become: true
  gather_facts: true
  tasks:
    - name: Install DO metrics
      ansible.builtin.get_url:
        url: https://repos.insights.digitalocean.com/install.sh
        dest: /tmp/do-agent-install.sh
        mode: "0755"
    - name: Run DO metrics installer
      ansible.builtin.command: /tmp/do-agent-install.sh
      args:
        creates: /etc/systemd/system/do-agent.service
    - name: Remove installer
      ansible.builtin.file:
        path: /tmp/do-agent-install.sh
        state: absent
