---
- name: Install AWS CLI
  hosts: centos_docker
  become: yes
  gather_facts: yes
  tasks:
    - name: Download AWS CLI
      shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - name: Unzip AWS CLI
      shell: unzip awscliv2.zip
    - name: Run installer
      shell: ./aws/install
    - name: Remove zip file
      shell: rm awscliv2.zip
- name: Install Digital Ocean metrics
  hosts: centos_docker
  become: yes
  gather_facts: yes
  tasks:
    - name: Install DO metrics
      shell: curl -sSL https://repos.insights.digitalocean.com/install.sh | sudo bash