---
- name: Update existing dependencies
  hosts: centos_docker
  become: yes
  gather_facts: yes
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest
- name: Install dependencies
  hosts: centos_docker
  become: yes
  gather_facts: no
  tasks:
    - name: Install python3
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: python3
        update_cache: yes
        state: present
    - name: Install vim
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - vim
          - vim-enhanced
        state: latest
        update_cache: true
    - name: Install epel-release
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - epel-release
        state: latest
        update_cache: true
    - name: Install htop
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - htop
        state: latest
        update_cache: true
    - name: Install utils
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - unzip
        state: latest
        update_cache: true
- name: Install docker
  hosts: centos_docker
  become: yes
  gather_facts: yes
  tasks:
    - name: Add CentOS_o repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: Install docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: docker-ce
        update_cache: yes
        state: present
    - name: Starting docker service
      service:
        name: "docker"
        state: started
        enabled: yes
- name: Install AWS CLI
  hosts: centos_docker
  become: yes
  gather_facts: yes
  tasks:
    - name: Download AWS CLI
      shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - name: Unzip AWS CLI
      shell: unzip awscliv2.zip
    - name: Run installer
      shell: ./aws/install
    - name: Remove zip file
      shell: rm awscliv2.zip
- name: Install Digital Ocean metrics
  hosts: centos_docker
  become: yes
  gather_facts: yes
  tasks:
    - name: Install DO metrics
      shell: curl -sSL https://repos.insights.digitalocean.com/install.sh | sudo bash

- name: Install telegraf
  hosts: centos_docker
  become: yes
  gather_facts: yes
  tasks:
    - name: Add CentOS_o repository
      shell: cat <<EOF | sudo tee /etc/yum.repos.d/influxdb.repo
        [influxdb]
        name = InfluxDB Repository - RHEL \$releasever
        baseurl = https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
        enabled = 1
        gpgcheck = 1
        gpgkey = https://repos.influxdata.com/influxdata-archive_compat.key
        EOF
    - name: Install influxdb
      yum:
        name: influxdb
        update_cache: yes
        state: present
    - name: Starting docker service
      service:
        name: "influxdb"
        state: started
        enabled: yes