---
- name: Update existing dependencies
  hosts: centos
  become: true
  gather_facts: true
  tasks:
    - name: Upgrade all packages
      ansible.builtin.yum:  # noqa package-latest
        name: "*"
        state: latest
        update_cache: true
