---
- name: Update existing dependencies
  hosts: centos
  become: yes
  gather_facts: yes
  tasks:
    - name: upgrade all packages
      ansible.builtin.yum:
        name: "*"
        state: latest
