---
- name: Add devops group
  hosts: ubuntu
  become: yes
  tasks:
    - name: Create devops group
      ansible.builtin.group:
        name: devops
        state: present

    - name: Create devops user
      ansible.builtin.user:
        name: devops
        group: devops
