---
- name: Fix locale
  hosts: ubuntu
  become: true
  tasks:
    - name: Gen locale
      ansible.builtin.command: locale-gen "en_US.UTF-8"
      changed_when: false
    - name: Reconfigure locale
      ansible.builtin.command: dpkg-reconfigure locales
      changed_when: false
